Expansions on the init script.
Not sure of the original author... Was in place in prod. Shrug?
Made it specify the shell, so "su" could work reliably.

diff --git a/islandora_microservices b/islandora_microservices
--- a/islandora_microservices
+++ b/islandora_microservices
@@ -24,6 +24,11 @@ CONFIG_FILE=$MICROSERVICES_PATH/islandora_microservices.cfg
 FEDORA_USER=fedora
 LISTENER_LINE="$PYTHON ./islandora_listener.py -C $CONFIG_FILE"
 LISTENER_LINE_ENVED="/usr/bin/screen -d -m /bin/env PATH=\"$PATH\" $LISTENER_LINE"
+SU_SHELL=/bin/sh
+
+START_STOP_WAIT=60
+FEDORA_SERVER_ADDRESS=localhost
+STOMP_PORT=61613
 
 start () {
 	echo -n "Starting $PROG: "
@@ -31,8 +36,22 @@ start () {
 	if pgrep -fx "$LISTENER_LINE" >/dev/null 2>&1; then
 		echo "$PROG is already running"
 	else
+		startwait=$START_STOP_WAIT
+		count=0
+		## Check to make sure that activeMQ has started for $START_STOP_WAIT seconds
+		while [ $count -lt $startwait ]; do
+			echo -n "."
+			count=`expr $count + 1`
+			ACTIVEMQ_CHECK=`nmap -p$STOMP_PORT $FEDORA_SERVER_ADDRESS | grep $STOMP_PORT | awk '{ print $2 }'`
+			sleep 1
+			if [ $ACTIVEMQ_CHECK = "open" ]; then
+				sleep 10
+				break
+			fi
+		done
+		if [ $ACTIVEMQ_CHECK = "open" ]; then
 			# start JMS as the fedora user
-     			su --session-command="cd $MICROSERVICES_PATH && $LISTENER_LINE_ENVED &" $FEDORA_USER #> /dev/null #2>&1
+     			su --shell=$SU_SHELL --session-command="cd $MICROSERVICES_PATH && $LISTENER_LINE_ENVED &" $FEDORA_USER #> /dev/null #2>&1
 			sleep 3
 			if pgrep -fx "$LISTENER_LINE" >/dev/null 2>&1; then
 				#su --session-command="touch $LOCK_FILE" $FEDORA_USER
@@ -40,7 +59,11 @@ start () {
 			else
 				echo -e "                                          [ \033[0;31m FAILED\033[0;39m""  ]"
 			fi
+		else
+			echo "" ; echo "$PROG was unable to contact the ActiveMQ broker running at $FEDORA_SERVER_ADDRESS."
+			exit 1
 		fi
+	fi
 }
 
 stop () {
@@ -49,7 +72,7 @@ stop () {
 	# check to see if the process is running
 	if pgrep -fx "$LISTENER_LINE" >/dev/null 2>&1; then
 		# use kill -2 to stop JMS.
-		if su --session-command="pkill -fx \"$LISTENER_LINE\"" $FEDORA_USER &>/dev/null; then
+		if su --shell=$SU_SHELL --session-command="pkill -fx \"$LISTENER_LINE\"" $FEDORA_USER &>/dev/null; then
 			echo -e "                                          [ \033[0;32m OK\033[0;39m""  ]"
                         #su --session-command="rm -f $LOCK_FILE" $FEDORA_USER
 		else
